development:
  cloud_name: <%= Rails.application.credentials.cloudinary.fetch(:cloud_name) %>
  api_key: <%= Rails.application.credentials.cloudinary.fetch(:api_key) %>
  api_secret: <%= Rails.application.credentials.cloudinary.fetch(:api_secret) %>
  secure: true

test:
  cloud_name: <%= Rails.application.credentials.cloudinary.fetch(:cloud_name) %>
  api_key: <%= Rails.application.credentials.cloudinary.fetch(:api_key) %>
  api_secret: <%= Rails.application.credentials.cloudinary.fetch(:api_secret) %>
  secure: true

production:
  cloud_name: <%= Rails.application.credentials.cloudinary.fetch(:cloud_name) %>
  api_key: <%= Rails.application.credentials.cloudinary.fetch(:api_key) %>
  api_secret: <%= Rails.application.credentials.cloudinary.fetch(:api_secret) %>
  secure: true